# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2634c0bebef389cddc7938d347ca98606b1ac059dd2a0f0eb0b972b1e9aab65cce3f9bcfa1d5df1898a93011c2dc5a98bffc9d3aba23e08c0356a62d1d8354d4

test:
  secret_key_base: 244760cd49ef64fcd6febe30f78e57ce2b96e1bbe27a033ab63098bbdff738de9110f7848860d17f80705741402dacc799238a1cde39df50498f2f4bea698de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
